on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    name: Build and Publish NuGet Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: extract_version
        run: |
          TAG=${GITHUB_REF#refs/tags/v}
          echo "Version tag: $TAG"
          IFS='.' read -r MAJOR MINOR PATCH <<< "$TAG"
          echo "MAJOR=$MAJOR" >> "$GITHUB_ENV"
          echo "MINOR=$MINOR" >> "$GITHUB_ENV"
          echo "PATCH=$PATCH" >> "$GITHUB_ENV"

      - name: Set version in csproj
        run: |
          for file in *.csproj; do
            sed -i "s|<Major>.*</Major>|<Major>${MAJOR}</Major>|" "$file"
            sed -i "s|<Minor>.*</Minor>|<Minor>${MINOR}</Minor>|" "$file"
            sed -i "s|<Build>.*</Build>|<Build>${PATCH}</Build>|" "$file"
            sed -i "s|<Version>.*</Version>|<Version>${MAJOR}.${MINOR}.${PATCH}</Version>|" "$file"
          done

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack
        run: dotnet pack --configuration Release --no-build --output ./nupkg

      - name: Push to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
